language: ruby
sudo: false
git:
  depth: 1
branch:
  only:
    - master
before_install:
- travis_retry gem install jekyll
- travis_retry gem install html-proofer
rvm:
- 2.3.3
script: jekyll build --safe && htmlproofer ./_site
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
      - irc.freenode.net#georchestra
    template:
      - "%{repository}#%{build_number} (%{branch}) %{message} %{build_url}"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
