# Site settings
title: geOrchestra Spatial Data Infrastructure
email: psc@georchestra.org
description: "geOrchestra is the free, modular, interoperable & secure Spatial Data Infrastructure made by people for people"
username: georchestra
baseurl: ""
url: "http://www.georchestra.org"
port: 4001

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

excerpt_separator: <!--more-->

safe: true
